name: KeepAlive

on:
  schedule:
    - cron: "*/8 * * * *"

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Wake app
        run: |
          for i in 1 2 3
          do
            curl -L \
              -H "User-Agent: Mozilla/5.0" \
              https://compliance-rag.streamlit.app/
            sleep 15
          done
